spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-132.railway.app:5632/railway
    username: postgres
    password: KfL4VgJZa5MLEuA0XiWC
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
