spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-199.railway.app:5723/railway
    username: postgres
    password: g8x0LEjnaUkaklDzaz7L
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect